version = 1

test_patterns = ["test/**"]

exclude_patterns = [
    "src/_locales/**",
    "src/img/**",
    "docs/**",
    ".github/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]